config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show, :edit, :update]
  get '/my_page' => 'users#my_page'

  root to: redirect("/#{I18n.default_locale}"), as: :redirected_root

  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    resources :posts, param: :slug
    root 'articles#index'
  end

  post 'articles/attach', to: 'articles#attach'

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :articles
      resources :users
    end
  end
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id            :bigint           not null, primary key
#  content_en    :text(65535)
#  content_ja    :text(65535)
#  content_zh_tw :text(65535)
#  main_language :integer          not null
#  status        :integer          default("published"), not null
#  title_en      :string(255)
#  title_image   :string(255)
#  title_ja      :string(255)
#  title_zh_tw   :string(255)
#  visible_list  :boolean          default(TRUE), not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :integer          not null
#
class Article < ApplicationRecord
  belongs_to :user
  has_one :place, dependent: :destroy
  accepts_nested_attributes_for :place

  has_many :comments, dependent: :destroy

  enum main_language: { japanese: 0, taiwanese: 1, english: 2 }
  enum status: { published: 0, draft: 1 }

  mount_uploader :title_image, TitleImageUploader

  acts_as_taggable_on :japan_tags, :taiwan_tags

  scope :visible, -> { where(visible_list: true) }
  scope :recent, -> { order(id: "DESC") }

  PER_PAGE = 9

  def self.tag_counts_on_locale(language)
    if language == 'ja'
      tag_counts_on(:japan_tags)
    else
      tag_counts_on(:taiwan_tags)
    end
  end

  def tag_counts_on_locale(language)
    if language == 'ja'
      tag_counts_on(:japan_tags)
    else
      tag_counts_on(:taiwan_tags)
    end
  end

  def translate_title_and_content
    translate_client = Aws::Translate::Client.new(
      region: "ap-northeast-1",
      access_key_id: Rails.application.credentials.dig(:aws, :access_key_id),
      secret_access_key: Rails.application.credentials.dig(:aws, :secret_access_key)
    )

    replace_tag = '<span translate=no>a123z</span>'

    if main_language_japanese?
      target_title = title_ja
      no_translate_array = no_translate_array_scan(content_ja)
      # マークダウンの#と画像ファイルを翻訳しないようにする
      target_content = content_ja.gsub(
        %r{(^#+ )|(!\[file\]\(.+\))|(<iframe.*</iframe>)|(<blockquote.*</blockquote>.<script async src="//www.instagram.com/embed.js"></script>)}, replace_tag
      )
      source_language_code = "ja"
      target_language_code = "zh-TW"
    else
      target_title = title_zh_tw
      no_translate_array = no_translate_array_scan(content_zh_tw)
      # マークダウンの#と画像ファイルを翻訳しないようにする
      target_content = content_zh_tw.gsub(
        %r{(^#+ )|(!\[file\]\(.+\))|(<iframe.*</iframe>)|(<blockquote.*</blockquote>.<script async src="//www.instagram.com/embed.js"></script>)}, replace_tag
      )
      source_language_code = "zh-TW"
      target_language_code = "ja"
    end

    response_title = translate_client.translate_text({
                                                       text: target_title,
                                                       source_language_code: source_language_code,
                                                       target_language_code: target_language_code
                                                     })

    response_content = translate_client.translate_text({
                                                         text: target_content,
                                                         source_language_code: source_language_code,
                                                         target_language_code: target_language_code
                                                       })

    # <p translate=no>とそれに紐づく</p>を削除
    translated_title = response_title.translated_text.gsub(%r{(<span translate=no>|</span>)}, '')
    translated_content = response_content.translated_text.gsub(%r{(<span translate=no>|</span>)}, '')

    no_translate_array.each do |text|
      translated_content.sub!(/a123z/, text)
    end

    @temp4 = translated_content

    if main_language_japanese?
      self.title_zh_tw = translated_title
      self.content_zh_tw = translated_content
    else
      self.title_ja = translated_title
      self.content_ja = translated_content
    end
  end

  def locale_judge_title(language)
    title = case language
            when 'ja'
              title_ja
            else
              title_zh_tw
            end
    # contentがblankなら空白を返す
    return '' if title.blank?

    title.gsub(%r{(<span translate=no>|</span>)}, '')
  end

  def locale_judge_content(language)
    content = case language
              when 'ja'
                content_ja
              else
                content_zh_tw
              end
    # contentがblankなら空白を返す
    return '' if content.blank?

    content
  end

  def display_translate_caution(language)
    if language == 'ja' && main_language == "taiwanese"
      "※この記事は機械翻訳された文章です"
    elsif language != 'ja' && main_language == "japanese"
      "※這篇文章是機器翻譯的句子"
    else
      ""
    end
  end

  private

  def main_language_japanese?
    main_language == "japanese"
  end

  def no_translate_array_scan(content)
    content.scan(%r{^#+ |!\[file\]\(.+\)|<iframe.*</iframe>|<blockquote.*</blockquote>.<script async src="//www.instagram.com/embed.js"></script>})
  end
end

app/controllers/api/v1/articles_controller.rb
module Api
  module V1
    class ArticlesController < ApplicationController
      skip_before_action :authenticate_user!, only: %i[index]
      before_action :set_article
      before_action :set_article_json

      def index
        render json: set_article_json
      end

      def set_article
        @articles = Article.all.visible.published.recent
      end

      def set_article_json
        options = { include: %i[user] }
        serializer = ArticleSerializer.new(@articles, options)
        serializer.serializable_hash.to_json
      end
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[ index show ]
  before_action :set_article, only: %i[ show edit update destroy translate_content]
  after_action :translate_contents, only: %i[ create update ], if: -> { @article.published? }

  # GET /articles or /articles.json
  def index
    @articles = Article.visible.published.recent.page(params[:page]).per(Article::PER_PAGE)
    # @tags = Article.tag_counts_on_locale(@locale).order('count DESC').limit(30)

    return if params[:tag_name].blank?

    tagged_article = Article.published.visible.recent.tagged_with(params[:tag_name].to_s).distinct
    if tagged_article.present?
      @articles = tagged_article.page(params[:page]).per(Article::PER_PAGE)
    else
      flash[:notice] = "タグの記事は存在しません"
    end
  end

  # GET /articles/1 or /articles/1.json
  def show
    @user = @article.user
    @tags = @article.tag_counts_on_locale(@locale)
    @articles = Article.visible.published.where.not(id: @article.id).order("RAND()").limit(3)
    return if browsing_authority?

    flash[:notice] = "この記事を閲覧する権限がありません"
    redirect_to user_path(@user)
  end

  # GET /articles/new
  def new
    @article = Article.new
    @article.build_place
  end

  # GET /articles/1/edit
  def edit
    @user = @article.user
    return if @user == current_user

    flash[:notice] = "この記事を編集する権限がありません"
    redirect_to article_path(@article)
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    @article.main_language = current_user.native_language

    if params[:publish]
      @article.status = "published"
      notice = t('helpers.message.create')
    elsif params[:draft]
      @article.status = "draft"
      notice = t('helpers.message.draft')
    end

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: notice }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    if params[:publish]
      @article.status = "published"
      notice = t('helpers.message.update')
    elsif params[:draft]
      @article.status = "draft"
      notice = t('helpers.message.draft')
    end

    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: notice }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @user = @article.user
    if @user != current_user
      flash[:notice] = "この記事を削除する権限がありません"
      redirect_to article_path(@article)
    else
      @article.destroy
      respond_to do |format|
        format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
        format.json { head :no_content_ja }
      end
    end
  end

  def attach
    attachment = Attachment.create!(article_image: params[:image])
    render json: { filename: attachment.article_image.url }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = "記事は存在しません。"
    Bugsnag.notify(ActiveRecord::RecordNotFound)
    redirect_to root_url
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title_ja, :content_ja, :title_zh_tw, :content_zh_tw, :title_image, :japan_tag_list,
                                    :taiwan_tag_list,
                                    place_attributes: [:id, :country, :prefecture_japan_id, :prefecture_taiwan_id])
  end

  def translate_contents
    @article.translate_title_and_content
    @article.update(article_params)
  end

  def browsing_authority?
    @article.published? || @article.draft? && current_user == @user
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_author.html.erb
<div class="flex w-full items-center font-sans px-4 py-4">
  <%= link_to user_path(user) do %>
    <% if user&.avatar.present? %>
      <%= image_tag user.avatar.url, class: "w-20 h-20 rounded-full mr-4" %>
    <% end %>
  <% end %>
  <div class="flex-1 px-2">
    <span class="flex pb-1">
    <%= link_to user_path(user) do %>
      <p class="text-base font-bold md:text-xl"><%= user&.name %></p>
    <% end %>
      <div class = "pl-2">
        <% if user.facebook.present? %>
          <a href=<%= user.facebook %> class="ml-3 text-gray-500">
            <i class="fab fa-facebook"></i>
          </a>
        <% end %>
        <% if user.twitter.present? %>
          <a href=<%= user.twitter %> class="ml-3 text-gray-500">
            <i class="fab fa-twitter"></i>
          </a>
        <% end %>
        <% if user.instagram.present? %>
          <a href=<%= user.instagram %> class="ml-3 text-gray-500">
            <i class="fab fa-instagram"></i>
          </a>
        <% end %>
        <% if user.youtube.present? %>
          <a href=<%= user.youtube %> class="ml-3 text-gray-500">
            <i class="fab fa-youtube"></i>
          </a>
        <% end %>
        <% if user.amazon.present? %>
          <a href=<%= user.amazon %> class="ml-3 text-gray-500">
              <i class="fab fa-amazon"></i>
          </a>
        <% end %>
      </div>
     </span>
    <p class="text-gray-600 text-xs md:text-sm leading-none">
      <%= user&.self_introduction %>
    </p>
  </div>
</div>

app/views/articles/_form.html.erb
<%= javascript_pack_tag 'article/image_upload_press_button' %>

<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- component -->
  <style>
      body {
          background: white !important;
      }
  </style>
  <div class="editor mx-auto w-10/12 flex flex-col text-gray-800 border border-gray-300 p-4 shadow-lg max-w-2xl">
    <div class="field bg-gray-100 border border-gray-300 p-2 mb-4 outline-none">
      <%= form.label "アイキャッチを設定してください" %>
      <%= form.file_field :title_image %>
      <!--      アップロードした画像があれば表示する-->
      <% if article.title_image.present? %>
        <%= image_tag article.title_image.url %>
      <% end %>
    </div>
    <div class="field bg-gray-100 border border-gray-300 p-2 mb-4 outline-none">
      <%= form.fields_for :place do |s| %>
        <%= s.label :国 %>
        <%= s.select :country, Place.countries.keys, { include_blank: "---" } %>

        <%= s.label :日本の場合 %>
        <%= s.collection_select(:prefecture_japan_id, PrefectureJapan.all, :id, :name, { include_blank: "---" }) %>

        <%= s.label :台湾の場合 %>
        <%= s.collection_select(:prefecture_taiwan_id, PrefectureTaiwan.all, :id, :name, { include_blank: "---" }) %>
      <% end %>
    </div>
    <div class="field bg-gray-100 border border-gray-300 p-2 mb-4 outline-none">
      <%= form.text_field :japan_tag_list, value: article.japan_tag_list.join(','), class: "bg-transparent w-full", placeholder: "japan tag1, tag2, max tag3" %>
      <ul class="tagit ui-widget ui-widget-content ui-corner-all">
        <li class="tagit-new">
          <%= form.text_field class: "ui-widget-content ui-autocomplete-input", autocomplete: "off", placeholder: "あああ" %>
        </li>
      </ul>
    </div>
    <div class="field bg-gray-100 border border-gray-300 p-2 mb-4 outline-none">
      <%= form.text_field :taiwan_tag_list, value: article.taiwan_tag_list.join(','), class: "bg-transparent w-full", placeholder: "taiwan tag1, tag2, max tag3" %>
    </div>

    <% if current_user.native_language == "japanese" %>
      <%= form.text_area :title_ja, class: "title bg-gray-100 border border-gray-300 p-2 mb-4 outline-none", spellcheck: "false", placeholder: "タイトル", type: "text" %>
      <%= form.text_area :content_ja, id: "text-editor", class: "uploadable description bg-gray-100 sec p-3 h-60 border border-gray-300 outline-none", spellcheck: "false", placeholder: "記事本文" %>
    <% else %>
      <%= form.text_area :title_zh_tw, class: "title bg-gray-100 border border-gray-300 p-2 mb-4 outline-none", spellcheck: "false", placeholder: "Title", type: "text" %>
      <%= form.text_area :content_zh_tw, id: "text-editor", class: "uploadable description bg-gray-100 sec p-3 h-60 border border-gray-300 outline-none", spellcheck: "false", placeholder: "Describe everything about this post here" %>
    <% end %>

    <!-- icons -->
    <div class="icons flex text-gray-500 m-2">
      <svg id="place" class="mr-2 cursor-pointer hover:text-gray-700 border rounded-full p-1 h-7" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"/>
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"/>
      </svg>
      <svg id="face" class="mr-2 cursor-pointer hover:text-gray-700 border rounded-full p-1 h-7" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>
      </svg>
      <svg id="image-up" class="mr-2 cursor-pointer hover:text-gray-700 border rounded-full p-1 h-7" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13"/>
      </svg>
      <div class="count ml-auto text-gray-400 text-xs font-semibold">0/300</div>
    </div>
    <!-- buttons -->
    <div class="buttons flex">
      <div class="btn border border-gray-300 p-1 px-4 font-semibold cursor-pointer text-gray-500 ml-auto"><%= form.submit "#{t('helpers.submit.draft')}", :name=> 'draft', :class => "font-semibold bg-transparent" %></div>
      <div class="btn border border-nittai_teal p-1 px-4 font-semibold cursor-pointer text-white ml-2 bg-nittai_teal"><%= form.submit :name=> 'publish', :class => "font-semibold text-white bg-nittai_teal" %></div>
    </div>
<% end %>
</div>
<br>

app/views/articles/_recommend_articles.html.erb
<section class="text-gray-600 body-font">
  <div class="container px-5 py-2 mx-auto">
    <p class="text-lg md:text-2xl font-normal font-bold mb-5"><%= t('helpers.recommend') %></p>
    <div class="flex flex-wrap -m-4">
      <% articles.each do |article| %>
        <%= link_to(article) do %>
          <div class="p-4 md:w-1/3">
            <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
              <% if article.title_image.present? %>
                <%= image_tag article.title_image.url, class: "lg:h-48 md:h-36 w-full object-cover object-center" %>
              <% else %>
                <img class="lg:h-48 md:h-36 w-full object-cover object-center" src="https://dummyimage.com/720x400" alt="blog">
              <% end %>
              <div class="p-6">
                <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">TITLE</h2>
                <h1 class="title-font text-lg font-medium text-gray-900 mb-3"><%= article.locale_judge_title(@locale) %></h1>
                <% if article.draft? %>
                  <p class="text-red-700 font-semibold"><%= "【#{t('helpers.submit.draft')}】" %></p>
                <% end %>
                <div class="markdown">
                  <%= markdown(article.locale_judge_content(@locale)).gsub(/<("[^"]*"|'[^']*'|[^'">])*>/, "").slice(0, 50) %>
                </div>
                <div class="flex items-center flex-wrap ">
                  <a class="text-blue-500 inline-flex items-center md:mb-2 lg:mb-0">
                  </a>
                  <p class="text-sm md:text-base font-normal text-gray-400">
                    <% if article.place&.country == "japan" %>
                      <%= "日本 #{article.place&.prefecture_japan&.name}" %>
                    <% elsif article.place&.country == "taiwan" %>
                      <%= "台灣 #{article.place&.prefecture_taiwan&.name}" %>
                    <% end %>
                  </p>
                </div>
                <% if article.tag_counts_on_locale(@locale).present? %>
                  <div class="flex items-center flex-wrap my-1">
                    <% article.tag_counts_on_locale(@locale).each do |tag| %>
                      <%= link_to tag.name, articles_path(tag_name: tag.name), method: :get, class: "m-0.5 bg-gray-200 hover:bg-gray-300 rounded-md px-2 text-xs leading-loose cursor-pointer" %>
                    <% end %>
                  </div>
                <% end %>
                <%= link_to(article.user) do %>
                  <span class="flex pt-1">
                    <%= image_tag article.user.avatar.url, class: "rounded-full h-10 w-10 border-2 border-white dark:border-gray-800" if article&.user&.avatar&.present? %>
                    <div class="text-xs md:text-sm font-normal text-gray-400 pl-1 my-auto">
                      <p><%= article.user&.name %></p>
                      <time datetime="<%= article.created_at %>">
                        <%= time_ago_in_words(article.created_at) %>前
                      </time>
                    </div>
                  </span>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/articles/edit.html.erb
<div class="heading text-center font-bold text-2xl m-5 text-gray-800">Edit Article</div>
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<section class="text-gray-600 body-font">
  <div class="container px-5 py-12 mx-auto">
    <%# if @tags.present? %>
<!--      <h3 class="flex justify-center items-center font-bold text-xs">TAGS</h3>-->
<!--      <div class="mb-4">-->
        <%# @tags.each do |tag| %>
<!--          <span class="m-1 bg-gray-200 hover:bg-gray-300 rounded-full px-2 font-bold text-sm leading-loose cursor-pointer">-->
<!--            #<%#= link_to "#{tag.name}(#{tag.taggings_count})", articles_path(tag_name: tag.name), method: :get %>-->
<!--          </span>-->
        <%# end %>
<!--      </div>-->
    <%# end %>
    <div class="flex flex-wrap -m-4">
      <% @articles.each do |article| %>
        <%= link_to(article) do %>
          <div class="p-4 md:w-1/3">
            <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
              <% if article.title_image.present? %>
                <%= image_tag article.title_image.url, class: "lg:h-48 md:h-36 w-full object-cover object-center" %>
              <% else %>
                <img class="lg:h-48 md:h-36 w-full object-cover object-center" src="https://dummyimage.com/720x400" alt="blog">
              <% end %>
              <div class="p-6">
                <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">TITLE</h2>
                <h1 class="title-font text-lg font-medium text-gray-900 mb-3"><%= article.locale_judge_title(@locale) %></h1>
                <div class="markdown">
                  <%= markdown(article.locale_judge_content(@locale)).gsub(/<("[^"]*"|'[^']*'|[^'">])*>/, "").slice(0, 50) %>
                </div>
                <div class="flex items-center flex-wrap">
                  <p class="text-sm md:text-base font-normal text-gray-400">
                    <% if article.place&.country == "japan" %>
                      <%= "日本 #{article.place&.prefecture_japan&.name}" %>
                    <% elsif article.place&.country == "taiwan" %>
                      <%= "台灣 #{article.place&.prefecture_taiwan&.name}" %>
                    <% end %>
                  </p>
                </div>
                <% if article.tag_counts_on_locale(@locale).present? %>
                  <div class="flex items-center flex-wrap my-1">
                    <% article.tag_counts_on_locale(@locale).each do |tag| %>
                      <%= link_to tag.name, articles_path(tag_name: tag.name), method: :get, class: "m-0.5 bg-gray-100 hover:bg-gray-200 rounded-md px-2 text-xs leading-loose cursor-pointer" %>
                    <% end %>
                  </div>
                <% end %>
                <%= link_to(article.user) do %>
                  <span class="flex pt-1">
                    <%= image_tag article.user.avatar.url, class: "rounded-full h-10 w-10 border-2 border-white dark:border-gray-800" if article.user&.avatar&.present? %>
                    <div class="text-xs md:text-sm font-normal text-gray-400 pl-1 my-auto">
                      <p><%= article.user&.name %></p>
                      <time datetime="<%= article.created_at %>">
                        <%= time_ago_in_words(article.created_at) %>前
                      </time>
                    </div>
                  </span>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <%= paginate @articles %>
  </div>
</section>

app/views/articles/new.html.erb
<div class="heading text-center font-bold text-2xl m-5 text-gray-800">New Article</div>
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<%= javascript_pack_tag 'article/markdown_for_iframe' %>

<% set_meta_tags title: @article.locale_judge_title(@locale), description: markdown(@article.locale_judge_content(@locale)).gsub(/<("[^"]*"|'[^']*'|[^'">])*>/, ""), og: { title: @article.locale_judge_title(@locale), image: @article.title_image.url } %>

<body class="bg-gray-100 font-sans leading-normal tracking-normal">
  <div class="container w-full md:max-w-3xl mx-auto pt-8">
    <div class="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal" style="font-family:Georgia,serif;">
      <div class="font-sans">
        <% if current_user&.admin? && current_user == @article.user %>
          <%= link_to 'Edit', edit_article_path(@article) %>
          <%= link_to 'Destroy', article_path(@article), method: :delete, data: { confirm: "本当に削除しますか？" } %>
        <% end %>
        <% if @article.draft? %>
          <p class="text-2xl md:text-3xl text-red-700 font-semibold pt-3"><%= "【#{t('helpers.submit.draft')}】" %></p>
        <% end %>
        <% if @article.title_image.present? %>
          <%= image_tag @article.title_image.url %>
        <% end %>
        <h1 class="font-bold font-sans break-normal text-gray-900 pt-6 pb-2 text-2xl md:text-3xl">
          <%= @article.locale_judge_title(@locale) %>
        </h1>
        <p class="text-lg md:text-xl font-normal text-red-700">
          <%= @article.display_translate_caution(@locale) %>
        </p>
        <p class="text-sm md:text-base font-normal text-gray-600">
          <% if @article.place&.country == "japan" %>
            <%= "日本 #{@article.place&.prefecture_japan&.name}" %>
          <% elsif @article.place&.country == "taiwan" %>
            <%= "台灣 #{@article.place&.prefecture_taiwan&.name}" %>
          <% end %>
        </p>
        <% if @tags.present? %>
          <div class="flex items-center flex-wrap my-1">
            <% @tags.each do |tag| %>
              <%= link_to tag.name, articles_path(tag_name: tag.name), method: :get, class: "m-0.5 bg-gray-200 hover:bg-gray-300 rounded-md px-2 text-xs leading-loose cursor-pointer" %>
            <% end %>
          </div>
        <% end %>
        <span class="flex pt-1">
          <%= link_to(@article.user) do %>
            <%= image_tag @article.user.avatar.url, class: "rounded-full h-10 w-10 border-2 border-white dark:border-gray-800" if @article&.user&.avatar&.present? %>
          <% end %>
          <div class="text-xs md:text-sm font-normal text-gray-400 pl-1 my-auto">
            <%= link_to(@article.user) do %>
              <p><%= @article.user&.name %></p>
            <% end %>
            <time datetime="<%= @article.created_at %>">
              <%= I18n.l(@article.created_at.in_time_zone('Asia/Tokyo'), format: :long) %>
            </time>
          </div>
          <div class="ml-auto mr-4 my-auto text-gray-400">
            <a href="https://www.facebook.com/share.php?u=<%= request.url %>" rel="nofollow" target="_blank"><i class="fab fa-facebook"></i></a>
            <a href="https://twitter.com/share?url=<%= request.url %>"><i class="fab fa-twitter ml-2"></i></a>
            <a href="https://line.me/R/msg/text/?<%= request.url %>"><i class="fab fa-line ml-2"></i></a>
          </div>
        </span>
      </div>

      <div id="markdown_iframe" class="markdown">
        <%= markdown(@article.locale_judge_content(@locale)) %>
      </div>
    </div>

    <br>
    <hr class="border-b-2 border-gray-400 mb-1 mx-4">
    <%= render 'author', user: @user %>
    <hr class="border-b-2 border-gray-400 mb-8 mx-4">
  </div>
</body>

<%= render 'recommend_articles', articles: @articles %>